package gui;

import dominio.Missao;
import dominio.Ninja;
import java.awt.Toolkit;
import java.util.ArrayList;
import textFileApp.ReadTextFile;

/**
 *
 * @authors Alexandre Roque, Henrique Coelho, Nasser Rafael, Ronaldo Zica e Vitor Santana.
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initListaNinjas();
        initListaMissoes();
        initComponents();
        initInternalFrames();
        setIconImage();
    }
    
    public void initListaMissoes(){
        ReadTextFile.openFile("listaMissoes.txt");
        missoes = ReadTextFile.readRecordsMissoes();
        ReadTextFile.closeFile();
    }
    
    public void initListaNinjas(){
        ReadTextFile.openFile("listaNinjas.txt");
        ninjas = ReadTextFile.readRecordsNinjas();
        ReadTextFile.closeFile();
    }
    
    public void initInternalFrames(){
        telaNinja = new TelaNinja(this.ninjas);
        telaMissao = new TelaMissao(this.missoes);
        painelPrincipal.add(telaNinja);
        painelPrincipal.add(telaMissao);
    }

    public ArrayList<Missao> getMissoes() {
        return missoes;
    }

    public void setMissoes(ArrayList<Missao> missoes) {
        this.missoes = missoes;
    }

    public ArrayList<Ninja> getNinjas() {
        return ninjas;
    }

    public void setNinjas(ArrayList<Ninja> ninjas) {
        this.ninjas = ninjas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        listaNinjas = new javax.swing.JButton();
        listaMissoes = new javax.swing.JButton();
        cadastroMissoes = new javax.swing.JButton();
        cadastroNinjas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aldeia da Folha");

        painelPrincipal.setPreferredSize(new java.awt.Dimension(670, 356));

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        listaNinjas.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        listaNinjas.setText("Lista de Ninjas");
        listaNinjas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listaNinjas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaNinjasActionPerformed(evt);
            }
        });

        listaMissoes.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        listaMissoes.setText("Lista de Missões");
        listaMissoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listaMissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMissoesActionPerformed(evt);
            }
        });

        cadastroMissoes.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        cadastroMissoes.setText("Cadastro de Missões");
        cadastroMissoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cadastroNinjas.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        cadastroNinjas.setText("Cadastro de Ninjas");
        cadastroNinjas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaMissoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaNinjas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroMissoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroNinjas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaNinjas)
                        .addGap(18, 18, 18)
                        .addComponent(listaMissoes)
                        .addGap(18, 18, 18)
                        .addComponent(cadastroNinjas)
                        .addGap(18, 18, 18)
                        .addComponent(cadastroMissoes)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaNinjasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaNinjasActionPerformed
        fechaInternalFrames();
        telaNinja.show();
    }//GEN-LAST:event_listaNinjasActionPerformed

    private void listaMissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMissoesActionPerformed
        fechaInternalFrames();
        telaMissao.show();
    }//GEN-LAST:event_listaMissoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaPrincipal janela = new JanelaPrincipal();
                janela.setVisible(true);
            }
        });
    }
    
    private void fechaInternalFrames(){
        telaNinja.dispose();
        telaMissao.dispose();
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/simboloFolha.png")));
    }
    
    private ArrayList<Missao> missoes;
    private ArrayList<Ninja> ninjas;
    
    private javax.swing.JInternalFrame telaNinja;
    private javax.swing.JInternalFrame telaMissao;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroMissoes;
    private javax.swing.JButton cadastroNinjas;
    private javax.swing.JButton listaMissoes;
    private javax.swing.JButton listaNinjas;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
