package gui;

import dominio.ControleMissoes;
import dominio.ControleNinjas;
import dominio.ControleNinjas;
import dominio.Missao;
import dominio.Ninja;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JLabel;
import textFileApp.ReadTextFile;


/**
 *
 * @authors Alexandre Roque, Henrique Coelho, Nasser Rafael, Ronaldo Zica e Vitor Santana.
 */
public class JanelaPrincipal extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form JanelaPrincipal
     */
    
    public JanelaPrincipal(ControleNinjas controleNinja, ControleMissoes controleMissoes) {
        this.controleNinja = controleNinja;
        this.controleMissoes = controleMissoes;
        initListaNinjas();
        initListaMissoes();
        initComponents();
        initInternalFrames();
        setIconImage();
        controleNinja.addObserver((Observer) telaNinja);
    }
    
    public void initListaMissoes(){
        ReadTextFile.openFile("listaMissoes.txt");
        missoes = ReadTextFile.readRecordsMissoes();
        ReadTextFile.closeFile();
    }
    
    public void initListaNinjas(){
        
        controleNinja.lerDadosNinja();
       
    }
    
    public void initInternalFrames(){
        telaNinja = new TelaNinja(this.controleNinja);
        telaMissao = new TelaMissao(this.controleMissoes);
        telaCadastroNinjas = new TelaCadastroNinjas(this.controleNinja);
        telaCadastroMissoes = new TelaCadastroMissoes();
        painelPrincipal.add(telaNinja);
        painelPrincipal.add(telaMissao);
        painelPrincipal.add(telaCadastroNinjas);
        painelPrincipal.add(telaCadastroMissoes);
        
        fechaInternalFrames();
    }

    public ArrayList<Missao> getMissoes() {
        return missoes;
    }

    public void setMissoes(ArrayList<Missao> missoes) {
        this.missoes = missoes;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        imagemVila = new javax.swing.JLabel();
        listaNinjas = new javax.swing.JButton();
        listaMissoes = new javax.swing.JButton();
        cadastroMissoes = new javax.swing.JButton();
        cadastroNinjas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aldeia da Folha");

        painelPrincipal.setPreferredSize(new java.awt.Dimension(670, 356));

        imagemVila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/aldeiaFundo.jpg"))); // NOI18N

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(imagemVila)
                .addGap(0, 165, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(imagemVila)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        listaNinjas.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        listaNinjas.setText("Lista de Ninjas");
        listaNinjas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listaNinjas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaNinjasActionPerformed(evt);
            }
        });

        listaMissoes.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        listaMissoes.setText("Lista de Missões");
        listaMissoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listaMissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMissoesActionPerformed(evt);
            }
        });

        cadastroMissoes.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        cadastroMissoes.setText("Cadastro de Missões");
        cadastroMissoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastroMissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroMissoesActionPerformed(evt);
            }
        });

        cadastroNinjas.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        cadastroNinjas.setText("Cadastro de Ninjas");
        cadastroNinjas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cadastroNinjas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroNinjasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listaMissoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listaNinjas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroMissoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastroNinjas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaNinjas)
                        .addGap(18, 18, 18)
                        .addComponent(listaMissoes)
                        .addGap(18, 18, 18)
                        .addComponent(cadastroNinjas)
                        .addGap(18, 18, 18)
                        .addComponent(cadastroMissoes)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaNinjasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaNinjasActionPerformed
        imagemVila.setVisible(false);
        fechaInternalFrames();
        telaNinja.show();
    }//GEN-LAST:event_listaNinjasActionPerformed

    private void listaMissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMissoesActionPerformed
        imagemVila.setVisible(false);
        fechaInternalFrames();
        telaMissao.show();
    }//GEN-LAST:event_listaMissoesActionPerformed

    private void cadastroNinjasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroNinjasActionPerformed
        imagemVila.setVisible(false);
        fechaInternalFrames();
        telaCadastroNinjas.show();  
    }//GEN-LAST:event_cadastroNinjasActionPerformed

    private void cadastroMissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroMissoesActionPerformed
        imagemVila.setVisible(false);
        fechaInternalFrames();
        telaCadastroMissoes.show();
    }//GEN-LAST:event_cadastroMissoesActionPerformed

    
    private void fechaInternalFrames(){
        telaNinja.dispose();
        telaMissao.dispose();
        telaCadastroNinjas.dispose();
        telaCadastroMissoes.dispose();
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/simboloFolha.png")));
    }   
     
    private ArrayList<Missao> missoes;
    
    private javax.swing.JInternalFrame telaNinja;
    private javax.swing.JInternalFrame telaMissao;
    private javax.swing.JInternalFrame telaCadastroNinjas;
    private javax.swing.JInternalFrame telaCadastroMissoes;
    private ControleNinjas controleNinja;
    private ControleMissoes controleMissoes;
    
    @Override
    public void update(Observable o, Object arg) {
        ControleNinjas controleAuxNinjas = (ControleNinjas)o;
        this.controleNinja = controleAuxNinjas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroMissoes;
    private javax.swing.JButton cadastroNinjas;
    private javax.swing.JLabel imagemVila;
    private javax.swing.JButton listaMissoes;
    private javax.swing.JButton listaNinjas;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
